name: ci
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build image
        run: docker build -t golden-path:ci .
      - name: Trivy scan
        uses: quasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.36.0
        with:
          image-ref: golden-path:ci
          severity: HIGH,CRITICAL